export enum productTypeEnums {
  VEGETABLES = 'VEGETABLES',
  CLOTHES = 'CLOTHES',
  TOYS = 'TOYS',
  GROCERIES = 'GROCERIES',
  SHOES = 'SHOES',
  // HAS_COLORS_AND_SIZES = 'HAS_COLORS_AND_SIZES',
  ELECTRONICS = 'ELECTRONICS',
}
